on:
  push:
  pull_request:

name: Build PDF documents

jobs:
  build_pdf:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Setup pandoc
        uses: nikeee/setup-pandoc@v1

      #- name: Setup TeX Live
      #  uses: teatimeguest/setup-texlive-action@v2

      - name: Install pdflatex, from https://gist.github.com/rain1024/98dd5e2c6c8c28f9ea9d
        run: |
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install texlive-latex-extra

      - name: Install pdfunite
        run: sudo apt-get install poppler-utils

      - name: Install bookletimposer
        run: sudo apt-get install bookletimposer

      - name: Remove old PDFs
        run: |
          cd boecker
          rm *.pdf
          cd ..

      - name: Create front pages
        run: |
          cd scripts
          ./goera_framsidor.sh
          cd ..

      - name: Show front pages
        run: |
          cd boecker
          ls *.pdf
          cd ..

      - name: Create books
        run: |
          cd scripts
          ./goera_bok_1.sh
          ./goera_bok_2.sh
          ./goera_bok_3.sh
          ./goera_bok_4.sh
          ./goera_bok_5.sh
          ./goera_bok_6.sh
          ./goera_bok_7.sh
          ./goera_bok_8.sh
          ./goera_test_bok.sh
          ./goera_bok_installera.sh
          cd ..

      - name: Show books
        run: |
          cd boecker
          ls *.pdf
          cd ..

      - name: Zip books
        run: |
          cd boecker
          zip processing_foer_undomar_boecker.zip *.pdf
          cd ..

      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v4
        with:
          name: processing_foer_ungdomar_boecker.zip
          path: boecker/processing_foer_undomar_boecker.zip

